apiVersion: v1
kind: Service
metadata:
  name: {{ include "eaglercraft.eaglercraft.fullname" . }}
  labels:
    {{- include "eaglercraft.eaglercraft.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.eaglercraft.service.port1 }}
    targetPort: game-port1
    protocol: TCP
    name: game-port1
  - port: {{ .Values.eaglercraft.service.port2 }}
    targetPort: game-port2
    protocol: TCP
    name: game-port2
  selector:
    {{- include "eaglercraft.eaglercraft.selectorLabels" . | nindent 4 }}
