apiVersion: v1
kind: Service
metadata:
  name: {{ include "eaglercraft.landingPage.fullname" . }}
  labels:
    {{- include "eaglercraft.landingPage.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.landingPage.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "eaglercraft.landingPage.selectorLabels" . | nindent 4 }}
