apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eaglercraft.nginxProxy.fullname" . }}-config
  labels:
    {{- include "eaglercraft.nginxProxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ tpl .Values.nginx.config . | indent 4 }}
