apiVersion: v1
kind: Service
metadata:
  name: {{ include "eaglercraft.nginxProxy.fullname" . }}
  labels:
    {{- include "eaglercraft.nginxProxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginxProxy.service.type }}
  ports:
  - port: {{ .Values.nginxProxy.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "eaglercraft.nginxProxy.selectorLabels" . | nindent 4 }}
